### ISSUE TITLE
Linear in what?

### ISSUE THREAD

**Issue by just-max** [cceh/suffix-tree#2]
Unfortunately, I was not able to construct a suffix tree in linear time using this library:

```python
import time
import random
from suffix_tree import Tree

random.seed(0)
words = [random.choices("abcdefghijklmnopqrstuvwxyz", k=random.randint(10, 20)) for _ in range(1000)]

result = []
for n in range(0, len(words) + 1, 50):
    it_words = words[:n]
    it_times = []
    for _ in range(3):
        start = time.process_time_ns()
        Tree(dict(enumerate(it_words)))
        end = time.process_time_ns()
        it_times.append(end - start)
    result.append((sum(map(len, it_words)), sum(it_times) / len(it_times)))
```

<details><summary>Results</summary>
<pre><code>0, 11649.666666666666
750, 46233650.333333336
1487, 89753019.66666667
2255, 161773125.66666666
2975, 258553530.0
3702, 358599287.6666667
4461, 458972382.0
5216, 608262643.3333334
5914, 758510699.3333334
6683, 961070447.3333334
7401, 1300382351.0
8162, 1550146969.0
8921, 1846915976.6666667
9662, 2192115563.0
10416, 2549625218.0
11208, 3017123428.0
11997, 3529445659.6666665
12719, 4047462716.0
13422, 5052296462.0
14168, 6944860159.666667
14922, 8248390707.333333
</code></pre>
</details>

![image](https://user-images.githubusercontent.com/17551908/192616820-1a6af8fe-b765-485a-aa46-2d2930e9a0eb.png)
(graph of 1.6239x10^8 * 1.00026^x - 4.7164*10^7)

**Comment by MarcelloPerathoner** [comment]
Linear in the sense that inserting a string of double length should take only double the time. I have just verified that it is indeed linear when inserting *one* string.
The behaviour you pointed out is surprising (at least for me) because inserting multiple strings uses the same code, and it should also behave linearly. I don't know what's happening there, I will look into it.
In the meantime, you should comment out all calls to the debug function. Some of the non-linearity may come from preparing the parameters for the debug function (even if they are not printed).

**Comment by just-max** [comment]
Interesting, thanks for looking into it. In the meantime I am using https://pypi.org/project/suffix-trees/, but I would prefer to use this library, since it can handle arbitrary sequences and doesn't rely on private use Unicode characters as delimiters.

I tried commenting out all the debug calls in `ukkonen.py`, which gives a slight speedup from what I can tell, but only be a constant factor (the runtime is still exponential).

**Comment by just-max** [comment]
Nice, thanks!
